/* Autogenerated by png2wx.pl on Mon Jun 16 11:41:33 2014 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_piman_pi;
extern wxBitmap *_img_piman;
extern wxBitmap *_img_piman_updates;

#endif /* ICONS_H */
