/* Autogenerated by png2wx.pl on Tue Jun 10 21:06:21 2014 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_piman_pi;
extern wxBitmap *_img_piman;

#endif /* ICONS_H */
